### PR TITLE
applied update for roblox process

### PR DESCRIPTION
**Pull request by sound-infinity**
I added a way to fetch the details of the processes, this gets the processes' name, PID, and memory usage.

With these details, the processes get sorted from highest to lowest memory usage. And, when the first result of ``(Roblox)(Player)Beta.exe`` is matched, it gets selected. 

The ``bWait`` function means "Blocked Wait" because I used os.clock and, while true do, in order to pause the script for some seconds. I made it mainly to wait for the cmd window to close, when opened by os.execute. And, surprisingly, it kinda adds some stability to the executor.

### CODE REVIEW

**Comment by sound-infinity** [comment]
This pull took a good time to set up

**Comment by bloxain** [comment]
Great I think this should be added because of the the issues  repeatedly being opened.

**Comment by thedoomed** [comment]
This looks really well done. Thank you and I can add this commit now. Sorry for the wait, just had a lot to do with my Celery project.

**Comment by sound-infinity** [comment]
@thedoomed Thank You! Though it would be better if you committed the newer one instead:
https://github.com/thedoomed/Cheat-Engine/pull/16/files

It is more stable and does not use ``while true do``

**Pull request closed without merging**
